spring.application.name=api-gateway
server.port=8765

#to regsiter api gateway to eureka
# eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

#enabling services to locate each other

#commenting this as we are routing the apis and making urls look simple
# spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
# spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
