spring.application.name=limit-service
spring.config.import=optional:configserver:http://localhost:8888
management.endpoints.web.exposure.include=refresh
management.endpoint.refresh.enabled=true
limits-service.maximum=998
limits-service.minimum=2