spring.application.name=currency-exchange
server.port=8000
management.endpoints.web.exposure.include=*
spring.config.import=optional:configserver:http://localhost:8888

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/currencyExchangeDb
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update

# spring.datasource.initialization-mode=always
# spring.jpa.defer-datasource-initialization=true

#number of attempts to be done
resilience4j.retry.instances.sample-api.max-attempts=5

#interval between hitting urls
resilience4j.retry.instances.sample-api.wait-duration=1s

#it will increase the wait time little extra
resilience4j.retry.instances.sample-api.enable-exponential-backoff=true

#failure-rate-threshold -> means when 80% of request will fail then circuit breaker will change 
#its state from close to open as intially its in close 
# resilience4j.circuitbreaker.instances.default.failure-rate-threshold=80

resilience4j.ratelimiter.instances.default.limit-for-period=2
resilience4j.ratelimiter.instances.default.limit-refresh-period=10s

#zipkin tracing and logging properties
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]
